name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AGENCY_AMOUNT=3
    networks:
      - testing_net
    volumes:
      - /home/fede/Uba/Distribuidos/tp0/tp/server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - /home/fede/Uba/Distribuidos/tp0/tp/client/config.yaml:/config.yaml
      - /home/fede/Uba/Distribuidos/tp0/tp/.data/agency-1.csv:/agency-1.csv

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - /home/fede/Uba/Distribuidos/tp0/tp/client/config.yaml:/config.yaml
      - /home/fede/Uba/Distribuidos/tp0/tp/.data/agency-2.csv:/agency-2.csv

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - /home/fede/Uba/Distribuidos/tp0/tp/client/config.yaml:/config.yaml
      - /home/fede/Uba/Distribuidos/tp0/tp/.data/agency-3.csv:/agency-3.csv


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24