name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /home/fede/server/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /home/fede/client/config.yaml

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Agustin Emanuel
      - APELLIDO=Zambrano
      - DOCUMENTO=30904466
      - NACIMIENTO=2000-03-17
      - NUMERO=7575
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /home/fede/client/config.yaml

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Federico Martín
      - APELLIDO=Valsagna Indri
      - DOCUMENTO=43030690
      - NACIMIENTO=2000-11-17
      - NUMERO=1314
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /home/fede/client/config.yaml

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Tiago Nicolás
      - APELLIDO=Rivera
      - DOCUMENTO=46060230
      - NACIMIENTO=1999-10-17
      - NUMERO=1413
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /home/fede/client/config.yaml

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Lionel Andrés
      - APELLIDO=Messi
      - DOCUMENTO=32020320
      - NACIMIENTO=1986-03-17
      - NUMERO=1010
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /home/fede/client/config.yaml

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

